"""
HackerOne submission formatter.

Formats findings into HackerOne-ready report drafts with
proper structure, severity mapping, and reproduction steps.
"""

from __future__ import annotations

import logging
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger("hunterengine.reporting.h1")

# HackerOne severity mapping
H1_SEVERITY_MAP = {
    "critical": "Critical",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "info": "None",
}

# CVSS-like impact descriptions
H1_IMPACT_MAP = {
    "critical": "This vulnerability allows complete compromise of the application's security posture.",
    "high": "This vulnerability has significant security impact and should be prioritized for remediation.",
    "medium": "This vulnerability has moderate impact and represents a meaningful security risk.",
    "low": "This vulnerability has limited direct impact but may contribute to attack chains.",
    "info": "This is an informational finding that may be useful for security hardening.",
}


class H1Formatter:
    """Format findings for HackerOne bug bounty submissions."""

    def __init__(self, output_dir: str | Path = "data/reports") -> None:
        self.output_dir = Path(output_dir) / "hackerone"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    async def format_all(self, findings: list[dict]) -> list[Path]:
        """Format all findings into individual H1 submission files."""
        paths = []
        # Only format findings worth submitting (medium+ confidence, not info)
        submittable = [
            f for f in findings
            if f.get("severity") != "info" and f.get("confidence", 0) >= 0.6
        ]

        for i, finding in enumerate(submittable, 1):
            path = self.format_single(finding, i)
            paths.append(path)

        logger.info(f"Formatted {len(paths)} HackerOne submissions")
        return paths

    def format_single(self, finding: dict, index: int = 1) -> Path:
        """Format a single finding into an H1 submission draft."""
        severity = finding.get("severity", "info")
        h1_severity = H1_SEVERITY_MAP.get(severity, "None")

        title = finding.get("title", "Untitled Finding")
        detector = finding.get("detector", "")
        url = finding.get("url", "")
        param = finding.get("parameter", "")

        lines = [
            f"# {title}",
            "",
            f"**Severity:** {h1_severity}",
            f"**Weakness:** {self._map_weakness(finding)}",
            "",
            "## Summary",
            "",
            finding.get("description", "No description provided."),
            "",
            "## Steps to Reproduce",
            "",
        ]

        # Build reproduction steps
        if finding.get("reproduction"):
            lines.append(finding["reproduction"])
        else:
            lines.extend(self._build_repro_steps(finding))

        lines.extend([
            "",
            "## Supporting Material / References",
            "",
        ])

        # Evidence
        if finding.get("evidence"):
            lines.extend([
                "### Evidence",
                "",
                "```",
                finding["evidence"][:3000],
                "```",
                "",
            ])

        # Request/Response
        if finding.get("request"):
            lines.extend([
                "### HTTP Request",
                "",
                "```http",
                finding["request"][:2000],
                "```",
                "",
            ])
        if finding.get("response"):
            lines.extend([
                "### HTTP Response",
                "",
                "```http",
                finding["response"][:2000],
                "```",
                "",
            ])

        # Impact
        lines.extend([
            "## Impact",
            "",
            finding.get("impact", H1_IMPACT_MAP.get(severity, "")),
            "",
        ])

        # Remediation
        if finding.get("remediation"):
            lines.extend([
                "## Recommended Fix",
                "",
                finding["remediation"],
                "",
            ])

        # References
        if finding.get("references"):
            lines.extend([
                "## References",
                "",
            ])
            for ref in finding["references"]:
                lines.append(f"- {ref}")
            lines.append("")

        # Metadata footer
        lines.extend([
            "---",
            f"*Generated by HunterEngine at {time.strftime('%Y-%m-%d %H:%M:%S')}*",
            f"*Detector: {detector} | Confidence: {finding.get('confidence', 0):.0%}*",
        ])

        # Write file
        safe_title = "".join(c if c.isalnum() or c in "-_ " else "" for c in title)[:60]
        filename = f"{index:03d}_{safe_title.replace(' ', '_')}.md"
        output_path = self.output_dir / filename
        output_path.write_text("\n".join(lines))

        return output_path

    def _build_repro_steps(self, finding: dict) -> list[str]:
        """Auto-generate reproduction steps from finding data."""
        steps = []
        url = finding.get("url", "")
        method = finding.get("method", "GET")
        param = finding.get("parameter", "")

        steps.append(f"1. Navigate to: `{url}`")

        if param:
            steps.append(f"2. Observe the parameter `{param}` in the {method} request")
            steps.append(f"3. Modify the parameter value as described in the evidence below")
        elif method != "GET":
            steps.append(f"2. Send a {method} request to the endpoint")

        steps.append(f"{'3' if not param else '4'}. Observe the response confirming the vulnerability")

        return steps

    @staticmethod
    def _map_weakness(finding: dict) -> str:
        """Map finding tags to HackerOne weakness types."""
        tags = set(finding.get("tags", []))
        tag_to_weakness = {
            "xss": "Cross-site Scripting (XSS) — Reflected",
            "cors": "CORS Misconfiguration",
            "ssrf": "Server-Side Request Forgery (SSRF)",
            "idor": "Insecure Direct Object Reference (IDOR)",
            "jwt": "Improper Authentication",
            "open-redirect": "Open Redirect",
            "prototype-pollution": "Prototype Pollution",
            "subdomain-takeover": "Subdomain Takeover",
            "secret": "Information Disclosure",
            "csp": "Content Security Policy Bypass",
            "race-condition": "Race Condition",
            "graphql": "GraphQL Vulnerability",
            "auth": "Authentication Bypass",
            "clickjacking": "Clickjacking",
        }
        for tag, weakness in tag_to_weakness.items():
            if tag in tags:
                return weakness
        return "Security Misconfiguration"
