program:
  name: Pulse BPI
  platform: Black Box Pentesting
  url: https://pulsebpi.com
in_scope:
  domains: []
  cidrs: []
  urls:
  - https://app.pulsebpi.com/login
out_of_scope:
  domains:
  - admin.example.com
  - vpn.example.com
  cidrs: []
  urls:
  - '*/logout'
  - '*/delete-account'
  keywords:
  - password_reset
  - delete
  - destroy
auth:
  type: none
  token: ''
  cookie: ''
  headers: {}
  login_url: ''
  credentials:
    username: ''
    password: ''
